# Name of your workflow
name: Deploy JavaScript App to GitHub Pages

on:
  # Runs on pushes to your default branch
  push:
    branches: ["main"] # Change this if your main branch is called 'master' or something else
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment, and cancel old ones
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Or the Node.js version your project uses
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        # This command builds your app. Check your package.json file's "scripts" 
        # section if 'npm run build' is not the correct command.
        run: npm run build 
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This should be the directory that your build process creates.
          # Based on your image, it is most likely the 'public' folder.
          # Common alternatives are 'build' or 'dist'.
          path: './public'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
